### ISSUE TITLE
First release checklist

### ISSUE THREAD

**Issue by sloede** [trixi-framework/libtrixi#98]
- [x] Create developer documentation on how to create a new release
- [x] Verify that [JuliaRegistrator](https://github.com/JuliaRegistries/Registrator.jl) is properly set up
- [x] Verify that [TagBot](https://github.com/JuliaRegistries/TagBot) is properly set up
- [x] Refer from LibTrixi.jl README to main README and main docs
- [x] Follow steps in developer docs to create a new release
- [x] Add reference to stable docs
- [x] Update repo link to point to stable docs
